GTnewsManager/Controllers/DownloadFileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GTnewsManager.Controllers
{
    public class DownloadFileController : Controller
    {
        // GET: DownloadFile
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult DownloadFile(string directoryName,string name)
        {
            string path = Server.MapPath(@"~\File\" + name);
            return File(path, "application/octet-stream");
        }
    }
}

GTnewsManager/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GTnewsManager.Controllers
{
    public class SearchController : Controller
    {
        // GET: Search
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Search()
        {
            //ViewBag.ResultMessage = TempData["ResultMessage"];
            //string xresult = "";
            List<FileInfo> result = new List<FileInfo>();
            //int i = 1;
            string rootpath = Request.PhysicalApplicationPath; //抓取專案所在實際目錄路徑
            DirectoryInfo docspath = new DirectoryInfo(rootpath + "File"); // 搭配專案相對應上傳的路徑
            FileInfo[] filelist = docspath.GetFiles();  //擷取目錄下所有檔案內容，並存到 FileInfo array
            //xresult = "<TABLE width=90% style='border:1px dashed #2f6fab; background-color: #eaf2d3;'>";
            //xresult += "<TR style='background-color:#5B9BD5;'><TD width='15%'>項次</TD><TD width='70%'>檔案名稱</TD><TD width='15%'>檔案大小</TD></TR>";
            //foreach (FileInfo fl in filelist)
            //{
                /*if (i % 5 == 0)  // 每五行以不同底色呈現表格樣式
                {
                    xresult += "<TR style='background-color:#ABC7E7;'><TD>" + i + "</TD><TD><a href='http://your_domain/Uploads/ " + fl.Name + "'>" + fl.Name + "</a></TD><TD>" + fl.Length + "</TD></TR>";
                }
                else
                {
                    xresult += "<TR><TD>" + i + "</TD><TD><a href='http:// your_domain /Uploads/" + fl.Name + "'>" + fl.Name + "</TD><TD>" + fl.Length + "</a></TD></TR>";
                }
                FileInfo fl
                i++;  //  顯示行號用之變數*/

            //}
            
            result = (from s in filelist select s).ToList();

            //xresult += "</TABLE>";
            return View(result);
        }
        public ActionResult DownloadFile(string directoryName, string name)
        {
            
            TempData["ResultMessage"] = "下載成功";
            string path = Server.MapPath(@"~\File\" + name);
            Stream istream = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.Read);
            
            return File(istream,"application/zip",name);
            
        }


        public ActionResult Upload()
        {
            ViewBag.ResultMessage = TempData["ResultMessage"];
            return View();
        }

        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase file)
        {
            if(file != null) { 
                if (file.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(file.FileName);
                    var path = Path.Combine(Server.MapPath("~/File"), fileName);
                    file.SaveAs(path);
                
                    TempData["ResultMessage"] = string.Format("檔案[{0}]上傳成功", fileName);
                }
            }
            return RedirectToAction("Search");
        }
        [HttpPost]
        public ActionResult Remove(string directoryName, string name)
        {
            List <FileInfo> result = new List<FileInfo>();
            //string rootpath = Request.PhysicalApplicationPath; //抓取專案所在實際目錄路徑
           // DirectoryInfo docspath = new DirectoryInfo(rootpath + "File"); // 搭配專案相對應上傳的路徑
            //FileInfo[] filelist = docspath.GetFiles();  //擷取目錄下所有檔案內容，並存到 FileInfo array
                                                        //result = (from s in filelist select s).ToList();
            //result = (from s in dbb select s).ToList();
            //var file = (from s in filelist where s.Name == name select s).FirstOrDefault();
            System.IO.File.Delete(@"" + directoryName + @"\" + name + @"");
            
            //dbb.RemoveAll(it => it.Name == name);
            //TempData["ResultMessage"] = @"" + directoryName + @"\" + name + @"";
            //result.Remove(file);
            return RedirectToAction("Search");
        }

      

    }
}

GTnewsManager/Views/Search/Search.cshtml
@model List<FileInfo>
@{
    ViewBag.Title = "Search";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div>
    @if (ViewBag.ResultMessage != null)//判斷如果有訊息，則顯示。
    {
        @Html.Label("info", (string)ViewBag.ResultMessage, new { @class = "text-info" })
    }

</div>
<div style="text-align:center;">
    <h2 class="alert-danger">素材及相關文件</h2>
</div>




<div class="form-group">
    <table class="table">
        <thead><tr><td>檔案名稱</td><td>檔案大小</td></tr></thead>
       
        <tbody>
            @foreach (var pd in this.Model)
            {
                float lenght = Convert.ToSingle(@pd.Length) / 1024 / 1024;
                <tr>
                    <td>
                        @pd.Name
                    </td>
                    <td>
                        @Math.Round(lenght, 4) MB
                    </td>
                    <td>
                        @Html.ActionLink("下載", "DownloadFile", new { directoryName = pd.DirectoryName, name = pd.Name }, new { @class = "btn btn-default" })
                    </td>
                    <td>
                        @using(@Html.BeginForm("Remove","Search",FormMethod.Post,new { @class = "Delete" }))
                        {
                            @Html.Hidden("directoryName", pd.DirectoryName);
                            @Html.Hidden("name", pd.Name);
                            <input type="submit" value="刪除" class="btn btn-default"/>
                        }
                        @*@Html.ActionLink("刪除檔案", "Remove", new { directoryName = pd.DirectoryName, name = pd.Name}, new { @class = "btn btn-default" })*@
                    </td>
                    <td>

                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<div class="form-group">

    <form action="@Url.Action("Upload")" method="post" enctype="multipart/form-data">
        <!--<div class="col-md-10">-->
            <h3 for="file">上傳檔案:</h3>
            <input type="file" name="file" id="file" />
            <input type="submit" class="btn btn-default" />
        <!--</div>-->
    </form>
</div>